version: '3'

services:  # Cambiado "service" a "services"
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:  # Cambiado "enviroment" a "environment"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data